version: '3'
services:
    app:
        build: .
#        depends_on:
 #       - db
        restart: always
        volumes:
        - ./app:/app

#    db:
 #       image: postgres:11
  #      environment:
   #      - POSTGRES_USER=postgres
    #     - POSTGRES_DB=postgres
